language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - ./test/test_setup/setup_hdfs.sh
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Elly"); Pkg.test("Elly"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Elly")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());'
